name: CD Pipeline - Deploy to Container Apps

on:
  workflow_run: 
    workflows: ["CI Pipeline - Build Docker Images"] 
    types:
    - completed

jobs: 
  deploy-backend:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
 
      - name: Deploy Backend to Container Apps
        run: |
          TAG=$(git rev-parse --short HEAD)
          az containerapp update \
            --name backend \
            --resource-group banana-project-rg \
            --image bananacnnproject.azurecr.io/backend:$TAG

  deploy-frontend: 
    runs-on: ubuntu-latest
    needs: deploy-backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Frontend to Container Apps
        run: |
          TAG=$(git rev-parse --short HEAD)
          az containerapp update \
          --name frontend \
          --resource-group banana-project-rg \
          --image bananacnnproject.azurecr.io/frontend:$TAG \
          --set-env-vars BACKEND_URL=https://backend.blackmeadow-fb3d881e.uksouth.azurecontainerapps.io