name: CD Pipeline - Deploy to Container Apps

on:
  workflow_run: 
    workflows: ["CI Pipeline - Build Docker Images"] 
    types:
    - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Containers to Container Apps
        run: |
          TAG=$(git rev-parse --short HEAD)
          az containerapp update \
            --name backend \
            --resource-group banana-project-rg \
            --image bananacnnproject.azurecr.io/backend:$TAG

          az containerapp update \
            --name frontend \
            --resource-group banana-project-rg \
            --image bananacnnproject.azurecr.io/frontend:$TAG