name: CI Pipeline - Build Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: ACR Login
      run: az acr login --name bananacnnproject

    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      # needs to be set up to enable caching
      uses: docker/setup-buildx-action@v3

    - name: Build backend image
      run: |
        TAG=$(git rev-parse --short HEAD)

        docker buildx build \
          --platform linux/amd64 \
          -f src/backend/Dockerfile \
          -t bananacnnproject.azurecr.io/backend:$TAG \
          --push \
          --cache-from=type=registry,ref=bananacnnproject.azurecr.io/backend:buildcache \
          --cache-to=type=registry,ref=bananacnnproject.azurecr.io/backend:buildcache,mode=max \
          .

    - name: Build frontend image
      run: |
        TAG=$(git rev-parse --short HEAD)

        docker buildx build \
          --platform linux/amd64 \
          -f src/frontend/Dockerfile \
          -t bananacnnproject.azurecr.io/frontend:$TAG \
          --push \
          --cache-from=type=registry,ref=bananacnnproject.azurecr.io/frontend:buildcache \
          --cache-to=type=registry,ref=bananacnnproject.azurecr.io/frontend:buildcache,mode=max \
          .
