name: CI Pipeline - Build Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: ACR Login
      run: az acr login --name bananacnnproject

    - uses: actions/checkout@v4
    - name: Build the Docker images
      run: |
        # git rev-parse -> resolve commit reference
        TAG=$(git rev-parse --short HEAD)

        docker buildx build \
        --platform linux/amd64 \
        -f src/backend/Dockerfile \
        -t bananacnnproject.azurecr.io/backend:$TAG \
        --push \
        .

        docker buildx build \
        --platform linux/amd64 \
        -f src/frontend/Dockerfile \
        -t bananacnnproject.azurecr.io/frontend:$TAG \
        --push \
        .
